mrgnlabs/mrgn-ts

packages/marginfi-client-v2/src/config.ts

After speaking more with @jkbpvsc it is still odd to write
`
const config = getConfig("production")
`
As a consumer, I'm not exactly sure what "production" implies. I also don't have access to the configs from the .env from the core team to see what else is changing. 
With getConfig being the default way I can access a MarginfiConfig object and the usage of getConfig spread out around the rest of the repo, I suggest adding a default parameter of "production" to remove the need for consumers to think about it. 
`
const config = getConfig()
` 
This should
- feel like more natural boiler plate code
- keep parity with internal usage of getConfig
- protect against future improvements to the interface (ex. "mainnet")

added a default value of production for the environment

---

apps/omni/src/api/ai/index.ts
apps/omni/src/pages/api/ai.ts
apps/omni/src/pages/index.tsx

- disable input when bot thinking or transaction pending
- add "repay" to supported regex
- bring back parsing of AI call for formatted action detection
- make formatted actions parsing stricter to avoid mistaken action trigger (e.g. when receiving a verbose account summary containing all the right keywords)
- make prompt reset less annoying
- add randomized prompt placeholder

disable input when bot thinking or transaction pending

---

.github/workflows/main.yml
apps/omni-xnft/App.tsx

ModuleNotFoundError: Module not found: Error: Can't resolve '../../App' in '/home/runner/work/mrgn-ts/mrgn-ts/apps/omni-xnft/node_modules/expo'
[expo / omni-xnft breaks cicd](https://github.com/mrgnlabs/mrgn-ts/actions/runs/5876769463/job/15935592445) and generally triggers my ocd
this PR fixes cicd build issue by creating a symbolic link at root of omni-xnft project `App.tsx` linking to `src/App.tsx`. expo requires App be imported from root of the project directory.
testing performed can be found here: https://github.com/AzothZephyr/mrgn-ts/actions/runs/5898533185

Fix cicd build issues

---

packages/marginfi-client-v2/src/models/balance.ts

SDK was calculating emissions for non 6 decimal banks incorrectly

fix: use bank decimals to scale emissions calc

---

apps/marginfi-v2-ui/src/components/common/PageHeader.tsx

feat(mrgn-v2-ui): mobile connect button

---

apps/marginfi-v2-ui/src/pages/points.tsx

Copy full referral url not just code.

fix(mfi-v2-xnft): full referral link url 

---

apps/marginfi-v2-ui/src/components/desktop/Points/PointsLeaderBoard.tsx
apps/marginfi-v2-ui/src/pages/points.tsx
apps/marginfi-v2-ui/src/utils/mrgnUtils.ts
packages/marginfi-v2-ui-state/src/lib/points.ts

- chore: remove deps causing leaderboard fetch to run additional times
- chore: remove unnecessary favorite domain call for connected user
- chore: refactor leaderboard fetch to batch sns domain lookups
- chore: revert all sns domain fetch, default to favorite > short address

chore(mfi-v2-ui): revert to favorite domain only, fallback to short address

---

apps/marginfi-v2-ui/src/hooks/useWalletContext.tsx
packages/mrgn-common/src/types.ts

- fix: signMessage in default adapters, add partial to type def
- chore: more robust type def for wallet variations

fix(mfi-v2-ui): explicitly define types in wallet def

---

apps/marginfi-v2-ui/src/components/common/AssetList/LSTDialog.tsx
apps/marginfi-v2-ui/src/components/common/Tutorial/Tutorial.tsx
apps/marginfi-v2-ui/src/components/ui/icons.tsx
apps/marginfi-v2-ui/tailwind.config.js

- chore: uncomment pwa banner, remove tutorial local storage check
- chore: switch LSTDialog to new dialog component
- chore: switch Tutorial to new dialog component
- fix: full width docs button on mobile tutorial
- chore: turn tutorial local storage check back on / remove pwa banner

chore(mfi-v2-ui): switch old dialogs to new shadcn components

---

apps/marginfi-v2-ui/src/components/common/AssetList/AssetListFilters.tsx
apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetRow/AssetRow.tsx

- chore: reduce table row padding
- chore: add render new asset banner

chore(mfi-v2-ui): new asset update - render

---

apps/marginfi-v2-ui/src/hooks/useWalletContext.tsx
apps/marginfi-v2-ui/src/store/lstStore.ts
apps/marginfi-v2-ui/src/store/uiStore.ts
packages/marginfi-v2-ui-state/src/store/jupiterStore.ts
packages/marginfi-v2-ui-state/src/store/mrgnlendStore.ts

- chore: dynamically load token data in lst store
- chore: refactor imports
- chore: change default sort option to match sdk

chore(mfi-v2-ui): perf improvements

---

apps/marginfi-v2-ui/src/utils/mrgnActions.ts
packages/marginfi-client-v2/src/client.ts
packages/marginfi-v2-ui-state/src/store/mrgnlendStore.ts

This fixes throwing an error when SquadsX signs because account is not found. This is because the transaction first needs to be executed by the multisig.

Fix SquadsX account creation issue

---

apps/marginfi-v2-ui/src/components/common/AssetList/NewAssetBanner.tsx
packages/marginfi-v2-ui-state/src/lib/points.ts

- chore: use session storage to hide new asset banner
- fix: add referral link to accounts with null points data

fix(mfi-v2-ui): various fixes

---

apps/marginfi-landing-page/src/components/Footer/Footer.tsx

Noticed that https://analytics.marginfi.com/ is currently broken, so perhaps it's better to direct users to the Grafana dashboard (linked in numerous places in the repo) for the time being.

fix: update analytics link

---

apps/marginfi-v2-ui/src/components/common/Bridge/Bridge.tsx
apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx

There were issues in the new bridge interface with the Mayan widget, causing it to be hidden. The issues are related to three main fixes:
- The Mayan widget now renders in a modal, which had issues that are resolved in the new version
- EVM RPC URLs seemed to have expired, so custom EVM RPCs were removed in favor of public RPCs to avoid maintenance issues
- The `-nowc` version of the Mayan widget is used, which does not have a `WalletConnect` dependency, avoiding multiple web-component issues with this package
Also added new supported tokens to the whitelisted mints (Drift, W, Jito, Jup).
Finally, the Mayan widget is enabled again.

Update Mayan widget version

---

package.json
yarn.lock

https://stackoverflow.com/questions/78566652/solana-web3-js-cannot-find-module-rpc-websockets-dist-lib-client

fix: use resoultion to target previous version of rpc-websockets before incompatible version

---

packages/marginfi-client-v2/src/models/price.ts

- fix: correct max confindence constant
- fix: multiply confidence intervals by constant

fix(marginfi-client-v2): pyth push price calcs

---

apps/marginfi-v2-trading/src/components/common/TradingBox/tradingBox.utils.tsx

the arena oracles will always be stale so no point of having this check anymore

feat(mfi-v2-trading): removed oracle staleness check

---

apps/marginfi-v2-docs/src/app/faqs/page.mdx

Adding Switchboard to list of our oracle providers in FAQ.

[Update] Adding Switchboard to oracle providers

---

apps/marginfi-v2-ui/src/components/common/Portfolio/PortfolioAssetCard.tsx
packages/mrgn-common/src/formatters.ts

Introduced a new function to dynamically display the tokenAmount based on the tokenprice. If the tokenPrice is defined, we calculate the smallest display unit we want to display & format it to that. Also has optional minimumDisplay, if the amount is smaller than that amount we return '<_minimumDisplay_' 
Currently implemented only on the portfolio, can do this throughout the entire app & replace the numeralFormatter whereever possible.

feat(mfi-v2-ui): introduce dynamic numeral formatter 

---

README.md
packages/marginfi-client-v2/package.json
packages/marginfi-client-v2/src/idl/marginfi-types.ts
packages/marginfi-client-v2/src/idl/marginfi.json
packages/marginfi-client-v2/src/models/bank.ts

Handles changes from https://github.com/mrgnlabs/marginfi-v2/pull/244 and https://github.com/mrgnlabs/marginfi-v2/pull/239, adding origination fees on borrow and program-level fees (paid to the program administrator) that are collected by a global fee wallet.
Changes:
- Banks have a new field: `bank.config.interest_rate_config.protocol_origination_fee` and `bank.collected_program_fees_outstanding`
- Groups have new fields: `group_flags` and `fee_state_cache`. 
- A new account called `FeeState` exists. This account is one-of-a-kind per program. 
- A new ix `init_global_fee_state` will run once after this program update, and then be removed from the program buffer in a subsequent update.
- A new FeeState admin-only ix `edit_global_fee_state` modifies program fees.
- A new FeeState …

Adds origination fee and program fee related updates

---

apps/marginfi-landing-page/src/components/header.tsx
apps/marginfi-landing-page/vercel.json

* add `vercel.json` that redirects to `marginfi.feather.blog` for `marginfi/blog`
* add Blog link to nav menu
resource: https://feather.so/help/how-to-configure-sub-folders-with-vercel

feature(marginfi-landing-page): add blog

---

packages/marginfi-v2-ui-state/src/lib/mrgnlend.ts

Checks liability shares instead of usd value to determine if position is lending / borrowing. Fixes reduce only borrows, with 0 state oracles, showing as lending positions unintentionally.

fix(mfi-v2-ui): reduce only positions

---

apps/marginfi-v2-ui/src/pages/ecosystem.tsx
yarn.lock

* add newer integration partners
* update integration descriptions

update(marginfi-v2-ui): update ecosystem page

---

apps/marginfi-v2-trading/src/pages/api/oracle/price.ts
apps/marginfi-v2-ui/src/pages/api/oracle/price.ts

Changelog: 
- Reduce `stale-while-revalidate` timing
- Take `s-maxage` (cache time) in consideration when calculating maxAge for oracles

chore(mfi-v2): update oracle price cache timing

---

packages/marginfi-v2-ui-state/src/lib/mrgnlend.ts

Default to checking against usdValues to account for active positions with zero asset / liab shares

fix(mfi-v2-ui): isLending check

---

packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/components/action-input/components/bank-select/components/bank-list/bank-list.tsx

This fix makes sure that if you borrow and asset you can't select it anymore to supply in looper and vice versa

fix(mfi-ui): not enough tokens disabled on looper

---

apps/marginfi-v2-ui/src/pages/api/tokens/multi.ts

- **chore: modify multi route to use edge function caching**
- **chore: commenting out dynamic code in multi route to enable edge runtime**

chore(mfi-v2-ui): multi route edge runtime

---

packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/deposit-swap-box.tsx
packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/hooks/use-deposit-swap-simulation.hooks.ts
packages/mrgn-ui/src/components/action-box-v2/actions/lend-box/hooks/use-lend-simulation.hooks.ts
packages/mrgn-ui/src/components/action-box-v2/actions/lend-box/lend-box.tsx
packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/loop-box.tsx
packages/mrgn-ui/src/components/action-box-v2/actions/repay-collat-box/repay-collat-box.tsx
packages/mrgn-ui/src/components/action-box-v2/actions/stake-box/stake-box.tsx

Not resetting additional action messages (aka errorMessage) when refetching mrgnlend state

fix(mfi-ui): no unnecessary resetting of additional action messages 

---

packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/deposit-swap-box.tsx
packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/hooks/use-deposit-swap-simulation.hooks.ts
packages/mrgn-utils/src/action-message.utils.ts
packages/mrgn-utils/src/actions/checks.ts

- Tailored canDepositSwap check: this was the issue that i mentioned during our chat. Updated the canDepositSwap to not look for the balance of the bank we were depositing into but to check the swapBank
- Not simulating when there are actionMessages that disable: unnecessarily running a simulation when there were actionMessages that prevent that simulation. Found this one using a whale wallet. He was borrowing sol, I tried to deposit-swap into sol, got an actionMessage but it still simulated the action
- Update filter of second inputField: I wasnt correctly filtering out the origin token, but that's updated now & we are filtering correctly

chore: QA changes on deposit-swap

---

apps/marginfi-v2-trading/src/components/common/trade-box-v2/hooks/use-trade-simulation.ts
apps/marginfi-v2-trading/src/components/common/trade-box-v2/trade-box.tsx
apps/marginfi-v2-trading/src/components/common/trade-box-v2/utils/trade-action.utils.ts
apps/marginfi-v2-trading/src/hooks/useMarginfiClient.tsx
packages/marginfi-client-v2/src/clients/client.ts
packages/marginfi-client-v2/src/services/transaction/helpers/tx-formatting.ts
packages/marginfi-client-v2/src/services/transaction/transaction.service.ts
packages/mrgn-common/src/modules/transactions/transaction.types.ts
packages/mrgn-utils/src/actions/flashloans/builders.ts
packages/mrgn-utils/src/actions/individualFlows.ts
packages/mrgn-utils/src/actions/types.ts

utilizes new transaction type to determine which transaction is being proccessed and adds an account key for arena transactions
there is some extra logic to add keys for LONG, SHORT and CLOSE_POSITIONS

feat: added arena tx tags to all marginfi transactions on the arena

---

apps/marginfi-v2-trading/src/components/common/Portfolio/PositionActionButtons.tsx
apps/marginfi-v2-trading/src/components/common/trade-box-v2/hooks/use-trade-simulation.ts
apps/marginfi-v2-trading/src/components/common/trade-box-v2/trade-box.tsx
apps/marginfi-v2-trading/src/components/common/trade-box-v2/utils/trade-action.utils.ts
apps/marginfi-v2-trading/src/hooks/useMarginfiClient.tsx
apps/marginfi-v2-ui/src/pages/deposit-swap.tsx
apps/marginfi-v2-ui/src/pages/looper.tsx
apps/marginfi-v2-ui/src/utils/actionBoxUtils.ts
packages/marginfi-client-v2/src/clients/client.ts
packages/marginfi-client-v2/src/services/transaction/helpers/tx-formatting.ts
packages/marginfi-client-v2/src/services/transaction/transaction.service.ts
packages/mrgn-common/src/modules/transactions/transaction.types.ts
packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/components/action-input/action-input.tsx
packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/components/action-input/components/bank-select/bank-select.tsx
packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/components/action-input/components/bank-select/components/bank-list/bank-list.tsx
packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/deposit-swap-box.tsx
packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/hooks/use-deposit-swap-simulation.hooks.ts
packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/store/deposit-swap-box-store.ts
packages/mrgn-ui/src/components/action-box-v2/actions/deposit-swap-box/utils/deposit-swap-action.utils.ts
packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/hooks/use-loop-simulation.hooks.ts
packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/loop-box.tsx
packages/mrgn-utils/src/action-message.utils.ts
packages/mrgn-utils/src/actions/checks.ts
packages/mrgn-utils/src/actions/flashloans/builders.ts
packages/mrgn-utils/src/actions/individualFlows.ts
packages/mrgn-utils/src/actions/types.ts

Changelog: 
- Passing in stakedAssetBanks to looper box 
- Checking & restricting depending if there are active stakedAssetBanks
- Not fetching transactions when there are actionMessages
- Restrict deposit-swap when the user has staked asset banks
- Reset banks when deposit-swap are the same
Arena changelog:
- added support for arena key tags

fix(mfi): looper staked-assets check & arena tag changes

---

apps/marginfi-v2-trading/src/components/common/Pool/PoolTradeHeader.tsx
apps/marginfi-v2-trading/src/components/common/Portfolio/LpActionButtons.tsx
apps/marginfi-v2-trading/src/components/common/Portfolio/PositionCard.tsx
apps/marginfi-v2-trading/src/components/common/Portfolio/PositionList/PositionListItem.tsx
apps/marginfi-v2-trading/src/components/common/Portfolio/components/close-position/close-position.tsx
apps/marginfi-v2-trading/src/components/common/admin/admin-pool-detail/pool-detail-card/pool-detail-card.tsx
apps/marginfi-v2-trading/src/components/common/trade-box-v2/trade-box.tsx
apps/marginfi-v2-trading/src/hooks/useActionBoxProps.tsx
apps/marginfi-v2-trading/src/hooks/useArenaClient.tsx
apps/marginfi-v2-trading/src/pages/api/processTransaction.ts
packages/marginfi-client-v2/src/clients/arena-client.ts
packages/marginfi-client-v2/src/clients/client.ts
packages/marginfi-client-v2/src/index.ts
packages/marginfi-client-v2/src/services/transaction/transaction.service.ts

This PR introduces arena client a seperate client that extends from the mrgnlend client and has some custom arena logic. This is done to prevent arena specific logic to get intertwined with mrgnlend logic.

feat(mfi-trading): introduction of arena client

---

README.md
apps/marginfi-v2-trading/README.md
apps/marginfi-v2-ui/README.md
packages/mrgn-ui/README.md
packages/tools/README.md
packages/tools/lib/list-tools.ts

- switches from yarn to pnpm
- adds readme doc

chore(tools): added docs

---

packages/mrgn-ui/src/components/action-box-v2/actions/lend-box/utils/lend-actions.utils.ts

Removes borrowOpts from lending actions that prevent unwrapping sol

fix(mfi-v2-ui): unwrap sol

---

packages/tools/TOOLS_README.MD
packages/tools/base-encoding/bs58tobs64.ts
packages/tools/luts/create_lut.ts
packages/tools/luts/update_lut.ts
packages/tools/mocks/mocks-do-nothing.ts
packages/tools/mocks/mocks.json
packages/tools/mocks/mocks.ts
packages/tools/scripts/accounts_ref.md
packages/tools/scripts/add_bank.ts
packages/tools/scripts/edit_fee_state.ts
packages/tools/scripts/fetch-bank.ts
packages/tools/scripts/fetch-group.ts
packages/tools/staging-deploy.json
packages/tools/svsp/LOCALNET_TESTING.MD
packages/tools/svsp/delegate_stake_acc.ts
packages/tools/svsp/deposit_single_pool.ts
packages/tools/svsp/init_single_pool.ts
packages/tools/svsp/init_stake_acc.ts
packages/tools/svsp/init_svsp_onramp.ts
packages/tools/svsp/init_validator.ts
packages/tools/svsp/send_mev.ts
packages/tools/svsp/stake-utils.ts
packages/tools/svsp/svsp_localnet_e2e.ts
packages/tools/svsp/svsp_replenish_pool.ts

*  Deploys the mock program to mainnet, adds some scripts to interact with the mock program
* The mock program can do nothing (fully supported!) or pretend to be a jup-like swap pool for testing flashloans and etc
* Fixes some issues with add_banks script following removal of oracles from this ix.
* Adds a script for dumping base58 from squads to examine the instruction info and simulate

Mock program scripts

---

apps/marginfi-v2-ui/src/pages/api/bundles/sendBundle.ts

This makes sure already processed bundles don't return a 500 error from the grpc endpoint

fix: improved bundles
