mrgnlabs/mrgn-ts

- apps/marginfi-v2-ui/src/pages/earn.tsx
resolves https://github.com/mrgnlabs/mrgn-ts/issues/49
> fix stage orb positioning

- apps/marginfi-landing-page/src/components/Footer/Footer.tsx
- apps/marginfi-landing-page/src/components/Navbar/Navbar.tsx
- apps/marginfi-landing-page/src/components/Navbar/NavbarCenterItem.tsx
- apps/marginfi-v2-ui/src/components/Navbar/Navbar.tsx
- apps/marginfi-v2-ui/src/components/Navbar/NavbarCenterItem.tsx
> [marginfi-v2-UI & marginfi-landing-page] Updating links and cleaning spacing

- packages/alpha-liquidator/src/index.ts
- packages/alpha-liquidator/src/inspect.ts
- packages/marginfi-client-v2/src/account.ts
- correctly compare assets and liabs for liquidation
- increase default min sol balance amount
> fix: is liquidatable check fix

- apps/marginfi-v2-ui/src/utils/formatters.ts
fix accidental negative $0 account balance
> Small change with the NumberFormat options

- apps/marginfi-v2-ui/src/context/Banks.tsx
- apps/marginfi-v2-ui/src/context/TokenMetadata.tsx
- apps/marginfi-v2-ui/src/utils/index.ts
Fetch token metadata from google cloud bucket instead local file.
> feat: token fetching from bucket cache

- apps/marginfi-v2-ui/src/pages/bridge.tsx
- Fix trigger solana wallet connection
- Remove widget `overflow:hidden` to fix the hidden tokens in the list
> Improve Mayan widget UI

- apps/marginfi-v2-ui/src/components/desktop/PageHeader.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileAssetsList/AssetCard/AssetCardPosition.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileAssetsList/MobileAssetsList.tsx
- apps/marginfi-v2-ui/src/pages/index.tsx
- apps/marginfi-v2-ui/src/pages/portfolio.tsx
- apps/marginfi-v2-ui/src/pages/swap.tsx
- Fixed refreshing bug
- decreased padding on mobile
- small portfolio improvements
- re-added mobile header
> fix(mfi-v2-ui): fix merge issues & bugfixes

- packages/marginfi-client-v2/package.json
- packages/marginfi-client-v2/src/client.ts
- packages/marginfi-client-v2/src/constants.ts
- Add a LUT for default group
- Automatically load LUTs in the client
- Compile all txs with the LUT
> Lookup table support

- apps/marginfi-v2-ui/src/components/common/AssetList/LSTDialog.tsx
- apps/marginfi-v2-ui/src/components/common/AssetList/index.ts
- apps/marginfi-v2-ui/src/components/common/Staking/StakingCard/StakingCard.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetRow/AssetRow.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetsList.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileAssetsList/AssetCard/AssetCard.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileAssetsList/MobileAssetsList.tsx
- apps/marginfi-v2-ui/src/pages/stake.tsx
- apps/marginfi-v2-ui/src/utils/mrgnActions.ts
Show popup with LST info and mint button when depositing / withdrawing SOL / stSOL. Add support for pre-selecting LST deposit token via URL.
> feat(mfi-v2-xnft): LST Popups

- apps/marginfi-v2-ui/src/utils/mrgnActions.ts
Fix borrow / lend error messages showing Undefined.
> fix(mfi-v2-ui): borrow / lend error msgs 

- apps/marginfi-v2-ui/src/pages/points.tsx
- apps/marginfi-v2-ui/src/pages/portfolio.tsx
Ensure user referral link has loaded before rendering copy ref link button.
> fix(mrgn-v2-ui): referral code copy

- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetRow/AssetRow.tsx
- apps/marginfi-v2-ui/src/components/desktop/DesktopNavbar/DesktopNavbar.tsx
- fix: always abbreviate numbers regardless of zoom level
- fix: increase zindex of desktop navbar
> fix(mrgn-v2-ui): borrow lend zoom overflow / zindex layering issues

- packages/marginfi-v2-ui-state/src/lib/points.ts
- fix: add 50ms delay to each iteration of sns check loop
- fix: increase sns throttle to 100ms
> fix(mfi-v2-ui): increase sns throttle time

- packages/marginfi-v2-ui-state/src/lib/points.ts
- fix: add 50ms delay to each iteration of sns check loop
- fix: increase sns throttle to 100ms
- fix: add missing await in sns throttle
> fix(mfi-v2-ui): add missing await in sns throttle

- apps/marginfi-v2-ui/package.json
- apps/marginfi-v2-ui/src/components/common/AccountSummary/UserStats.tsx
- apps/marginfi-v2-ui/src/components/common/Tutorial/Tutorial.tsx
- apps/marginfi-v2-ui/src/components/common/Tutorial/index.tsx
- apps/marginfi-v2-ui/src/components/common/icons/Alert.tsx
- apps/marginfi-v2-ui/src/components/common/icons/index.ts
- apps/marginfi-v2-ui/src/pages/_app.tsx
- apps/marginfi-v2-ui/src/styles/globals.css
- yarn.lock
- feat: basic ui for in-app tutorial dialog with swiper
- feat: add tutorial content
- feat: add warning to health factor tooltip
- feat: responsive tutorial
> feat(mfi-v2-ui): in-app tutorial v1

- apps/marginfi-v2-ui/src/components/common/Tutorial/Tutorial.tsx
- chore: tutorial copy update
- feat: switch tutorial to use localStorage instead of cookies
> fix(mfi-v2-ui): switch tutorial to localStorage + copy updates

- apps/marginfi-v2-ui/src/components/common/Tutorial/Tutorial.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/WalletIntroDialog.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/WalletOnramp.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/WalletPkDialog.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/index.tsx
- apps/marginfi-v2-ui/src/components/mobile/PWABanner/PWABanner.tsx
- apps/marginfi-v2-ui/src/components/mobile/PWABanner/index.tsx
- apps/marginfi-v2-ui/src/components/ui/icons.tsx
- apps/marginfi-v2-ui/src/components/ui/sheet.tsx
- chore: abstract pk dialog to separate sub component
- feat: funding wallet popup wip
- feat: pwa banner wip
- fix: correct tutorial bg color
- chore: funding wallet popup copy change, hide pwa banner for now
> feat(mfi-v2-ui): funding wallet popup, hidden pwa banner

- apps/marginfi-v2-ui/src/components/mobile/MobileNavbar/MobileNavbar.tsx
- apps/marginfi-v2-ui/src/components/mobile/PWABanner/PWABanner.tsx
- apps/marginfi-v2-ui/tailwind.config.js
- feat: switch pwa notice to header banner with local storage integration
- chore: only show pwa banner on ios
> feat(mfi-v2-ui): pwa banner on iOS devices

- apps/marginfi-v2-ui/package.json
- apps/marginfi-v2-ui/src/components/common/PageHeader.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/WalletOnramp.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileAssetsList/AssetCard/AssetCard.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileAssetsList/MobileAssetsList.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileNavbar/MenuModal.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileNavbar/MobileNavbar.tsx
- apps/marginfi-v2-ui/src/components/ui/select.tsx
- apps/marginfi-v2-ui/src/pages/index.tsx
- apps/marginfi-v2-ui/src/pages/portfolio.tsx
- apps/marginfi-v2-ui/tailwind.config.js
- yarn.lock
- feat: switch asset ordering dropdown to shadcn
- feat: disable my positions filter and trigger auth dialog when signed out
- feat: reduce padding on order by dropdown
- feat: improve responsive asset list
- chore: clean up grid / gutters
- chore: remove sign out from more menu
- feat: improve skeleton loading in asset grid
> feat(mfi-v2-ui): various mrgnmobile improvements

- apps/marginfi-v2-ui/src/components/common/Wallet/WalletPkDialog.tsx
- apps/marginfi-v2-ui/src/hooks/useWalletContext.tsx
- fix: store user email if available and pass to pk request reauth
- chore: left align pk in dialog
> fix(mfi-v2-ui): store email and pass to pk request reauth

- apps/marginfi-v2-ui/src/utils/toastUtils.tsx
- packages/marginfi-v2-ui-state/src/lib/mrgnlend.ts
- chore: remove autoclose from failed toasts
- chore: implement 10s abort controller and better structure promises to handle birdeye errors
> chore(mfi-v2-ui): better handle birdeye errors

- apps/marginfi-v2-ui/src/utils/toastUtils.tsx
- packages/marginfi-client-v2/src/client.ts
- packages/marginfi-client-v2/src/errors.ts
- packages/marginfi-client-v2/src/idl/marginfi-types.ts
- update marginfi contract error list
- throw error to toast when running simulation as well to help debugging
- make the error toast not auto-close (at least temporarily) to allow users to screenshot/feedback them to us
> fix(mfi-v2-ui): update mfi error list

- apps/marginfi-v2-ui/package.json
- apps/marginfi-v2-ui/src/components/desktop/Points/PointsSignIn.tsx
- apps/marginfi-v2-ui/src/components/desktop/Points/PointsSignUp.tsx
- apps/marginfi-v2-ui/src/hooks/useFirebaseAccount.tsx
- apps/marginfi-v2-ui/src/pages/api/user/login.ts
- apps/marginfi-v2-ui/src/pages/api/user/signup.ts
- apps/marginfi-v2-ui/src/pages/points.tsx
- packages/marginfi-v2-ui-state/src/lib/firebase.ts
- yarn.lock
- WIP: point fixes
- WIP: checkpoint
- fix(mfi-v2-ui): points improvement
- WIP: point fixes
> feat(mfi-v2-ui): combine sign in with wallet connect to remove need to authenticate for points

- apps/marginfi-v2-ui/src/components/common/AssetList/AssetListFilters.tsx
- apps/marginfi-v2-ui/src/components/common/AssetList/AssetListFilters.utils.tsx
- apps/marginfi-v2-ui/src/components/common/AssetList/NewAsssetBanner.tsx
- apps/marginfi-v2-ui/src/components/common/AssetList/index.ts
- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetRow/AssetRow.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetsList.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileAssetsList/MobileAssetsList.tsx
- apps/marginfi-v2-ui/src/components/ui/icons.tsx
- apps/marginfi-v2-ui/src/pages/index.tsx
- apps/marginfi-v2-ui/src/store/index.ts
- apps/marginfi-v2-ui/src/store/uiStore.ts
- apps/marginfi-v2-ui/src/types.ts
- feat: new asset banner (wip)
-  feat: ui for filter positions toggle / pool type dropdown
- feat: filter pools by type
- feat: move lending mode to uiStore and add to new asset banner controls
- feat: highlight asset in new asset banner controls
- feat: filter user positions
- chore: remove global pool option from pool type filter
> feat(mfi-v2-ui): pool filters

- apps/marginfi-v2-ui/src/components/common/AssetList/NewAsssetBanner.tsx
- apps/marginfi-v2-ui/src/components/desktop/DesktopAccountSummary/DesktopAccountSummary.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileAssetsList/AssetCard/AssetCard.tsx
- apps/marginfi-v2-ui/src/pages/index.tsx
- packages/marginfi-client-v2/src/models/account/pure.ts
- packages/marginfi-v2-ui-state/src/lib/firebase.ts
- chore: change name of asset banner local storage val
- fix: add asset-row data attr to mobile asset cards to fix scroll / highlight
- chore: remove debugs
> fix(mfi-v2-ui): new asset banner fixes / improvements

- apps/marginfi-v2-ui/src/pages/stake.tsx
- chore: stake copy updates
- chore: add validator link
- chore: stake copy update
> chore(mfi-v2-ui): stake copy

- apps/marginfi-v2-ui/src/components/common/AssetList/AssetList.utils.ts
This reverts commit 10e18f9e4b20e8093fd9665376a91626099ae3f9.
> fix(mfi-v2-ui): remove jto from swb banks

- apps/marginfi-v2-ui/src/components/common/AssetList/AssetList.utils.ts
- apps/marginfi-v2-ui/src/components/common/AssetList/index.ts
- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetRow/AssetRow.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileAssetsList/AssetCard/AssetCardHeader.tsx
- chore: dynamic oracle labels
- chore: transition dogwifhat image
> chore(mfi-v2-ui): dynamic oracle labels

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBox.tsx
- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBoxPreview.tsx
- apps/marginfi-v2-ui/src/components/common/Portfolio/AssetCard/AssetCard.tsx
- fix: action box preview health colors
- fix: orange apr
- chore: add half wallet amount option and fix vertical alignment
> chore(mfi-v2-ui): various ui improvements

- apps/marginfi-v2-ui/src/components/common/Tutorial/Tutorial.tsx
- apps/marginfi-v2-ui/src/components/desktop/Footer/Footer.tsx
- apps/marginfi-v2-ui/src/components/ui/badge.tsx
- apps/marginfi-v2-ui/src/components/ui/icons.tsx
- feat: tutorial pro mode slide
- feat: tutorial pro mode slide for existing users
> feat(mfi-v2-ui): pro mode popup

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBoxActions.tsx
- apps/marginfi-v2-ui/src/store/uiStore.ts
- chore: show connect wallet button in action box if unauthenticated
- chore: persist zustand ui store
> feat(mfi-v2-ui): various ux improvements

- apps/marginfi-v2-ui/src/components/desktop/DesktopNavbar/DesktopNavbar.tsx
- apps/marginfi-v2-ui/src/components/mobile/Points/MobilePointsOverview.tsx
- apps/marginfi-v2-ui/src/pages/_app.tsx
- apps/marginfi-v2-ui/src/pages/earn.tsx
- fix: mobile total points display
- chore: hide earn link if no deposits found
> chore(mfi-v2-ui): hide earn link

- apps/marginfi-v2-ui/src/components/common/Stats/Stats.tsx
- apps/marginfi-v2-ui/src/components/common/Tutorial/Tutorial.tsx
- feat: increase size of mobile stats
- chore: hide likte / pro modal on mobile
> feat(mfi-v2-ui): various mobile improvements

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBox.tsx
- apps/marginfi-v2-ui/src/components/ui/icons.tsx
- apps/marginfi-v2-ui/src/store/uiStore.ts
- apps/marginfi-v2-ui/src/utils/mrgnActions.ts
- packages/marginfi-client-v2/src/models/account/wrapper.ts
- feat: add priority fee button to action box ui
- feat: priority fees ui v1
> feat(mfi-v2-ui): priority fees

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBox.tsx
- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBoxPriorityFees.tsx
- apps/marginfi-v2-ui/src/components/common/ActionBox/index.tsx
- apps/marginfi-v2-ui/src/components/ui/icons.tsx
- feat: add accent border to priority fee options
- chore: abstract actionbox priorityfees sub component
- feat: add priority feel info tooltip
- feat: add back to lending / borrow button in priority fee dialog
> feat(mfi-v2-ui): priority fee ui feedback

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBox.tsx
- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBoxPriorityFees.tsx
- apps/marginfi-v2-ui/src/components/common/AssetList/AssetRowHeader.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetRow/AssetRow.tsx
- apps/marginfi-v2-ui/src/components/desktop/DesktopNavbar/DesktopNavbar.tsx
- apps/marginfi-v2-ui/src/components/desktop/Footer/Footer.tsx
- apps/marginfi-v2-ui/src/components/mobile/MobileNavbar/MenuModal.tsx
- apps/marginfi-v2-ui/src/mediaQueries.ts
- Revert "feat: careers links in header / mobile menu"
- chore: loop through priority fee options
- feat: remove pro table zoom settings
- feat: pro table refactor
> feat(mfi-v2-ui): pro table and various updates

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBoxPriorityFees.tsx
Fix priority fees ui to update fee on save only.
> fix(mfi-v2-ui): priority fees settings ui

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBox.tsx
- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBoxPreview.tsx
- apps/marginfi-v2-ui/src/components/common/Portfolio/Portfolio.tsx
- apps/marginfi-v2-ui/src/components/common/Stats/Stats.tsx
- packages/marginfi-v2-ui-state/src/lib/points.ts
- feat: switch total points to tvl in home page stats
- fix: ensure referral points not included in deposit / lend stats
- feat: hide portfolio if no open positions
- feat: various fixes / improvements to action box preview stats
> feat(mfi-v2-ui): various improvements

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBox.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx
- apps/marginfi-v2-ui/src/pages/bridge.tsx
- apps/marginfi-v2-ui/src/pages/swap.tsx
- apps/marginfi-v2-ui/src/utils/index.ts
- apps/marginfi-v2-ui/src/utils/mrgnActions.ts
- chore: move mrgn action analytics calls to actionbox component
- chore: remove wallet data storage from user
- feat: swap / bridge analytics events
> feat(mfi-v2-ui): ui analytics v2

- apps/marginfi-v2-ui/src/pages/ecosystem.tsx
- apps/marginfi-v2-ui/src/utils/analytics.ts
- fix: set autocpature to false
- fix: disable ph pagie view / leave autocapture
- fix: ecosystem proj name
> fix(mfi-v2-ui): disable posthog autocapture / ecosystem update

- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetRow/AssetRow.tsx
- apps/marginfi-v2-ui/src/hooks/useAssetItemData.ts
This PR adds the protocol fixed fee to a bank borrow apr if available. This PR also fixes oracle conditionals since an SDK change.
> fix(mfi-v2-ui): optional fixed fee in borrow apr

- apps/marginfi-v2-ui/next.config.js
- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBoxTokens.tsx
- apps/marginfi-v2-ui/src/components/common/ActionComplete/ActionComplete.tsx
- apps/marginfi-v2-ui/src/components/common/AssetList/LSTDialog.tsx
- apps/marginfi-v2-ui/src/components/common/AssetList/NewAssetBanner.tsx
- apps/marginfi-v2-ui/src/components/common/Portfolio/PortfolioAssetCard.tsx
- apps/marginfi-v2-ui/src/components/common/Staking/StakingCard/StakingCard.tsx
- apps/marginfi-v2-ui/src/components/common/Staking/StakingCard/StakingModal.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetRow/AssetRow.tsx
- apps/marginfi-v2-ui/src/utils/mrgnUtils.ts
This PR updates all references to token logos to use a public gcp box with the format {token symbol}.png
> chore(mfi-v2-ui): token logo gcp bucket

- packages/marginfi-client-v2/package.json
Signed-off-by: Shivam Sandbhor <shivam.sandbhor@gmail.com>
> chore(mfi-client-v2): add missing dep

- apps/marginfi-v2-ui/package.json
- yarn.lock
This reverts commit 9844953f31d4ec3e613504c2cdfc921178b3a0da.
> chore(mfi-v2-ui): revert moongate upgrade

- apps/marginfi-v2-ui/src/components/desktop/AssetsList/AssetRow/AssetRow.tsx
- apps/marginfi-v2-ui/src/styles/globals.css
- fix: usd denomination
- fix: body scroll issue
- fix: scrollbar styles
> fix(mfi-v2-ui): usd denomination / body scroll fixes

- apps/marginfi-v2-ui/package.json
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.old.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/WalletAvatar.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/WalletTokens.tsx
- apps/marginfi-v2-ui/src/components/ui/button.tsx
- apps/marginfi-v2-ui/src/components/ui/icons.tsx
- apps/marginfi-v2-ui/src/components/ui/sheet.tsx
- apps/marginfi-v2-ui/src/components/ui/tabs.tsx
- apps/marginfi-v2-ui/src/styles/globals.css
- yarn.lock
- feat: new wallet component, static header + tabs (wip)
- feat: wallet v2 token list view / receive copy address button (wip)
- feat: feat: wallet v2 token detail view (wip)
> feat: wallet v2 static ui

- apps/marginfi-v2-ui/src/components/common/Swap/Swap.tsx
- apps/marginfi-v2-ui/src/components/common/Swap/index.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx
- apps/marginfi-v2-ui/src/pages/swap.tsx
- apps/marginfi-v2-ui/src/styles/globals.css
- feat: portfolio / points updates (wip)
- feat: portfolio / points page updates (wip)
- feat: remove lite / pro mode
- feat: add new mint page
- chore: remove lite / pro mode
- chore: remove hotkeys
- fix: usd denomination
- feat: add usd denomination toggle to filters
- feat: add new footer
- fix: body scroll issue
- fix: scrollbar styles
- feat: add rank to wallet
- fix: white bg overflow
- chore: update nav with new links
- feat: unstake actionbox
- wip: mint page restructuring
- wip: mint page restructuring
- feat: mintpage layout refresh
- feat: new wallet component, static header + tabs (wip)
- feat: wallet v2 token list view / receive copy address button (wip)
- feat: feat: wallet v2 token detail view (wip)
- feat: deposit / borrow action box triggers in wallet token detail view
- …
> feat(mfi-v2-ui): wallet v2 swap

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBox.tsx
- apps/marginfi-v2-ui/src/components/common/Announcements/Announcements.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/components/WalletButton.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetList/utils/columnDataUtils.tsx
- fix: reduce action box border radius
- feat: dark theme wallet button
- feat: add disconnect option to mobile wallet
> feat(mfi-v2-ui): various updates

- apps/marginfi-v2-ui/src/components/common/Announcements/Announcements.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx
- apps/marginfi-v2-ui/src/components/ui/icons.tsx
- apps/marginfi-v2-ui/src/pages/index.tsx
- chore: refactor announcements flex styles
- fix: remove wallet address tooltip due to glitch on open
- feat: add points location announcement
> feat(mfi-v2-ui): announcements fixes / updates

- apps/marginfi-v2-ui/src/components/common/Announcements/Announcements.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx
- apps/marginfi-v2-ui/src/pages/index.tsx
- feat: add requiredAuth prop to announcements to remove hover state / click when unauthenticated
- fix: wallet tab alignment on small screens
> fix(mfi-v2-ui): various fixes

- apps/marginfi-v2-ui/src/components/common/Bridge/Bridge.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/Wallet.tsx
- apps/marginfi-v2-ui/src/components/common/Wallet/components/Authentication/WalletAuthAccounts.tsx
- apps/marginfi-v2-ui/src/components/ui/icons.tsx
- apps/marginfi-v2-ui/src/pages/api/user/account-label.ts
- apps/marginfi-v2-ui/src/pages/api/user/migrate-points.ts
- apps/marginfi-v2-ui/src/pages/api/user/signup.ts
- apps/marginfi-v2-ui/src/utils/mrgnActions.ts
- packages/marginfi-v2-ui-state/src/lib/firebase.ts
This PR extends the accounts switch dropdown to include edit / create account capabilities and enables it for all users.
> feat(mfi-v2-ui): sub accounts

- apps/marginfi-v2-ui/src/components/common/ActionBox/components/ActionBoxPreview/Components/LendingPreview/useLendingPreview.ts
- apps/marginfi-v2-ui/src/components/desktop/AssetList/AssetList.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetList/components/AssetCells.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetList/utils/tableHelperUtils.tsx
- apps/marginfi-v2-ui/src/utils/actionBoxUtils.ts
- simulation not resetting after action change
- various asset list fixes
- better warning message actionbox
> fix(mfi-v2-ui): various bugfixes

- apps/marginfi-landing-page-v2/src/app/layout.tsx
- apps/marginfi-landing-page-v2/src/components/callout.tsx
- apps/marginfi-landing-page-v2/src/components/features.tsx
- chore: remove inter font import
- feat: features typography improvements
- feat: callout typography improvements
> feat(mfi-landing-page-v2): hotfixes

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBox.tsx
- apps/marginfi-v2-ui/src/components/common/CongestionBanner/CongestionBanner.tsx
- apps/marginfi-v2-ui/src/components/common/CongestionBanner/index.tsx
- apps/marginfi-v2-ui/src/components/common/Navbar/Navbar.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetList/components/AssetCells.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetList/utils/columnDataUtils.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetList/utils/tableHelperUtils.tsx
- apps/marginfi-v2-ui/src/pages/_app.tsx
- apps/marginfi-v2-ui/src/store/uiStore.ts
- apps/marginfi-v2-ui/src/utils/actionBoxUtils.ts
- apps/marginfi-v2-ui/src/utils/mrgnUtils.ts
- yarn.lock
This PR switches stale oracle warnings back on with improved messaging, and adds a new network congestion banner shown if stale oracles > threshold.
> feat(mfi-v2-ui): stale oracle messaging

- apps/marginfi-v2-ui/src/components/common/ActionBox/ActionBoxDialog.tsx
- apps/marginfi-v2-ui/src/components/common/Announcements/Announcements.tsx
- apps/marginfi-v2-ui/src/pages/index.tsx
- fix: remove mother global pool announcement
- fix: mobile actionbox dialog overlay
- fix: announcement requires auth conditional preventing clicks from firing when unauthenticated
> fix(mfi-v2-ui): announcement banner fix and updates

- apps/marginfi-v2-trading/src/components/common/Pool/CreatePoolDialog.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/PoolSearch.tsx
- apps/marginfi-v2-trading/src/components/ui/dialog.tsx
- apps/marginfi-v2-trading/src/context/TradeProvider.tsx
- apps/marginfi-v2-trading/src/pages/index.tsx
- apps/marginfi-v2-trading/src/pages/pools/[symbol].tsx
- apps/marginfi-v2-trading/src/store/tradeStore.ts
- feat: create pool dialog states (wip)
- chore: store filteredBanks as empty array by default
- chore: only run fetch updates on trade page
- feat: hook up pool search with trade store
- feat: create pool search
- feat: create pool dialog search responsive styles
- feat: reset create pool search form on open
> feat(arrakeen): create pool dialog search

- apps/marginfi-v2-trading/public/tradingview/custom.css
- apps/marginfi-v2-trading/src/components/common/Header/Header.tsx
- apps/marginfi-v2-trading/src/components/common/Portfolio/PositionCard.tsx
- apps/marginfi-v2-trading/src/components/common/Portfolio/PositionList.tsx
- apps/marginfi-v2-trading/src/components/common/TVWidget/TVWidget.tsx
- apps/marginfi-v2-trading/src/pages/_app.tsx
- apps/marginfi-v2-trading/src/pages/index.tsx
- apps/marginfi-v2-trading/src/pages/pools/[symbol].tsx
- apps/marginfi-v2-trading/src/pages/portfolio.tsx
- apps/marginfi-v2-trading/src/pages/trade/[symbol].tsx
- apps/marginfi-v2-trading/src/styles/globals.css
- feat: trade page styling
- feat: trading view widget styling
- feat: positions list zero state
- fix: collateralBank fetching logic
> feat(arrakeen): trade page ui

- apps/marginfi-v2-trading/next.config.js
- apps/marginfi-v2-trading/src/components/common/Pool/CreatePoolDialog.tsx
- apps/marginfi-v2-trading/src/components/ui/dialog.tsx
- apps/marginfi-v2-trading/src/components/ui/form.tsx
- apps/marginfi-v2-trading/src/pages/api/asset-search.ts
- feat: asset-search das api wrapper
- feat: useForm integration (wip)
- chore: restructure form to move file upload within Form parent
- feat: add file upload to useForm schema
- feat: prefill decimals from token fetch step
- feat: pre-fill image from token fetch
- feat: enforce imageUpload or imageDownload in form schema refine
- fix: clean create pool form on dialog open and close
- fix: File type reference on server side
- feat: back buttons / rework mint search continue button logic
- chore: fix linting warnings and nextjs allowed remote paths
- feat: form validation
- feat: add oracle info link
- feat: loading / success states
- fix: remove extra active group reset
> feat(arrakeen): create pool ux

- apps/marginfi-v2-ui/src/components/common/ActionBox/components/ActionBoxTokens/Components/LoopingTokens/LoopingTokens.tsx
Allow all main pool tokens in looper, other than reduce-only / retiring.
> feat(mfi-v2-ui): main pool looper

- apps/marginfi-v2-ui/src/components/common/CongestionBanner/CongestionBanner.tsx
- apps/marginfi-v2-ui/src/utils/mrgnUtils.ts
- packages/marginfi-client-v2/src/client.ts
- packages/marginfi-client-v2/src/models/price.ts
- fix: stale oracle ui labels
- feat: decrease usdc oracle max age
- feat: add oracle timestamp to OraclePrice type, update stale calc
- chore: remove oracle debugging
- chore: remove tokendata debugging
> fix(mfi-v2-ui): stale oracle ui warnings

- apps/marginfi-v2-trading/src/components/common/ActiveGroup/ActiveGroup.tsx
- apps/marginfi-v2-trading/src/components/desktop/Footer/Footer.tsx
- apps/marginfi-v2-trading/src/pages/pools/[symbol].tsx
- feat: active group toggle
- fix: footer zindex
- feat: pool detail layout (wip)
- feat: new pool detail layout
> feat(arrakeen): new pool detail layout

- apps/marginfi-v2-trading/src/components/mobile/MobileNavbar/MobileNavbar.tsx
> bug(marginfi-v2-trading): fixes mobile navbar links and aesthetic

- apps/marginfi-v2-trading/src/components/common/Pool/PoolCard.tsx
- apps/marginfi-v2-trading/src/components/ui/select.tsx
- apps/marginfi-v2-trading/src/config/trade.ts
- apps/marginfi-v2-trading/src/pages/index.tsx
- apps/marginfi-v2-trading/src/store/tradeStore.ts
- feat: add "load more" button / "sort by" select static ui components
- feat: load more style pagination
- feat: sort pools
- feat: add support for asc / desc icons
- feat: add lastUPdate sorting
- chore: comment out test bank data
> feat(arrakeen): pagination / sorting pools

- apps/marginfi-v2-trading/package.json
- apps/marginfi-v2-trading/src/components/common/Pool/BankCard.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/PoolChart.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/PoolHeader.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/index.tsx
- apps/marginfi-v2-trading/src/components/common/TVWidget/TVWidgetTopBar.tsx
- apps/marginfi-v2-trading/src/components/ui/chart.tsx
- apps/marginfi-v2-trading/src/pages/api/birdeye/price-history.ts
- apps/marginfi-v2-trading/src/pages/api/birdeye/token.ts
- apps/marginfi-v2-trading/src/pages/pools/[symbol].tsx
- apps/marginfi-v2-trading/src/styles/globals.css
- apps/marginfi-v2-trading/src/types.ts
- yarn.lock
- feat: pool detail price area chart (wip)
- feat: pool detail price area chart labels / styling
> feat(arrakeen): pool detail price chart

- apps/marginfi-v2-trading/package.json
- apps/marginfi-v2-trading/src/components/common/Header/Header.tsx
- apps/marginfi-v2-trading/src/components/common/PageHeading/PageHeading.tsx
- apps/marginfi-v2-trading/src/components/desktop/Footer/Footer.tsx
- apps/marginfi-v2-trading/src/pages/index.tsx
- apps/marginfi-v2-trading/src/pages/pools/[symbol].tsx
- apps/marginfi-v2-trading/src/pages/portfolio.tsx
- apps/marginfi-v2-trading/src/pages/trade/[symbol].tsx
- yarn.lock
- feat: loading messages
- feat: install framer, slide in header on load
- feat: footer links / mrgn animation
- feat: framer motion landing page animations
- feat: improve animation syncing
- feat: delay footer animation
> featre(arrakeen): intro animation on landing page

- apps/marginfi-v2-trading/src/components/common/Header/Header.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/CreatePoolSoon/CreatePoolSoon.tsx
- fix: show create pool button when disconnected
- feat: add submitting state to create pool form
> fix(mfi-v2-trading): submit token form

- apps/marginfi-v2-trading/src/components/common/Pool/BankCard.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/PoolCard.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/PoolHeader.tsx
- apps/marginfi-v2-trading/src/components/common/Portfolio/PositionCard.tsx
- apps/marginfi-v2-trading/src/components/common/Portfolio/PositionList.tsx
- apps/marginfi-v2-trading/src/components/common/TVWidget/TVWidgetTopBar.tsx
- apps/marginfi-v2-trading/src/components/desktop/Footer/Footer.tsx
- apps/marginfi-v2-trading/src/components/ui/tooltip.tsx
- apps/marginfi-v2-trading/src/pages/api/birdeye/token.ts
- apps/marginfi-v2-trading/src/types.ts
- apps/marginfi-v2-trading/src/utils/errorUtils.ts
- apps/marginfi-v2-ui/src/components/common/ActionBox/components/ActionBoxPreview/Components/LoopPreview/useLoopingPreview.ts
- packages/mrgn-common/src/formatters.ts
- feat: add audits link to footer
- fix: race condition in bank card causing page to fail when active banks not set in time
- fix: 5 decimals for price only
- feat: add market cap to trade page stats
- fix: tooltip layering
- chore: remove birdeye data log
- fix: broken link in error messaging
> fix(mfi-v2-trading): various fixes

- apps/marginfi-v2-ui/src/components/desktop/AssetList/components/AssetCells.tsx
- apps/marginfi-v2-ui/src/components/desktop/AssetList/utils/columnDataUtils.tsx
- packages/marginfi-v2-ui-state/src/lib/mrgnlend.ts
- packages/marginfi-v2-ui-state/src/store/mrgnlendStore.ts
- chore: debugging pyusd apy issues
- chore: remove emissions debugging, add explanation
> fix(mfi-v2-ui): discrepencies in emissions apy

- apps/marginfi-v2-trading/src/components/desktop/Footer/Footer.tsx
- apps/marginfi-v2-trading/src/pages/portfolio.tsx
- apps/marginfi-v2-trading/src/store/tradeStore.ts
- fix: footer links
- chore: portfolio heading copy change
- fix: created_at ordering
> fix(mfi-v2-trading): various updates / fixes

- apps/marginfi-v2-trading/package.json
- apps/marginfi-v2-trading/src/components/common/ActionBox/ActionBox.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/CreatePoolSoon/CreatePoolSoon.tsx
- apps/marginfi-v2-trading/src/components/common/Portfolio/PositionActionButtons.tsx
- apps/marginfi-v2-trading/src/components/common/TradingBox/TradingBox.tsx
- apps/marginfi-v2-trading/src/pages/_app.tsx
- yarn.lock
Google Analytics / PostHog event tracking.
> feat(mfi-v2-trading): analytics config

- apps/marginfi-v2-ui/src/components/common/ActionComplete/ActionComplete.tsx
https://github.com/user-attachments/assets/fc212ebc-ea5d-4ba3-b593-d8be3bd08127
> feature(marginfi-v2-ui): add link to asgardfi heimdall in `ActionComplete`

- apps/marginfi-landing-page/src/app/layout.tsx
- apps/marginfi-v2-trading/src/context/TradeProvider.tsx
- apps/marginfi-v2-ui/src/context/MrgnlendProvider.tsx
- apps/marginfi-v2-ui/src/pages/_app.tsx
- feat: add google analytics to app / www
- feat: identify on wallet change
- feat: store wallet pk as custom prop
> feat: analytics updates

- apps/marginfi-v2-ui/src/pages/_app.tsx
CHANGELOG: 
- removed unused fetchMrgnLendState and asPath properties
- used correct ready state for GA, isReady (which was a useRouter state) might become `true` too early (before hydrating) which causes an hydration error
> fix: hydration error

- apps/marginfi-v2-ui/src/components/common/Portfolio/LendingPortfolio/LendingPortfolio.tsx
- apps/marginfi-v2-ui/src/components/common/Portfolio/PortfolioHeader.tsx
- apps/marginfi-v2-ui/src/pages/portfolio.tsx
- packages/mrgn-ui/src/components/wallet-v2/hooks/use-wallet.hook.tsx
- packages/mrgn-ui/src/components/wallet-v2/wallet.tsx
Changelog: 
- Moved loading states to main portfolio component instead of spread out over 3 components
- Handled all loading/completed states
- wallet connected, store loading, refreshing after connecting a wallet, no (filtered for the user) banks or final state where (filtered for the user) banks are loaded 
- Introduces a state with a timeout after the wallet has been connected. isStoreRefreshing isnt updated immediately after the wallet is connected, which caused the UI to be in a bad state. 
-> This will be removed once we've got a proper API implementation for the profile, but for now it prevents the flickering
> Portfolio fixes & states handling

- apps/marginfi-v2-ui/src/components/common/Portfolio/PortfolioAssetCard.tsx
- apps/marginfi-v2-ui/src/pages/index.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/lend-box/lend-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/loop-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-collat-box/repay-collat-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/components/action-button/action-button.tsx
- packages/mrgn-ui/src/components/action-box-v2/types/action-box.types.ts
- packages/mrgn-ui/src/components/wallet-v2/components/wallet-button/wallet-button.tsx
- packages/mrgn-ui/src/components/wallet-v2/hooks/use-wallet.hook.tsx
- packages/mrgn-ui/src/components/wallet-v2/wallet.tsx
- fix: working version fixing logout / address updating state issues
- fix: action button now using wallet button
- fix: remove auto connect after forcibly logging out
- chore: clean up use-wallet hook
- chore: remove onConnect from actionbox types
- fix: missing dep in create wallet context state use effect
> chore(mfi-ui): upgraded / optimized use-wallet hook

- packages/marginfi-v2-ui-state/src/lib/firebase.ts
- packages/mrgn-common/src/types.ts
- packages/mrgn-ui/src/components/wallet-v2/components/wallet-auth-accounts/wallet-auth-accounts.tsx
- packages/mrgn-ui/src/components/wallet-v2/wallet.tsx
Phantom wallet adapter returns an object w signature from signMessage, add support and fix account label update.
> fix(mfi-v2-ui): account labels

- apps/marginfi-v2-ui/src/hooks/useFirebaseAccount.tsx
- apps/marginfi-v2-ui/src/pages/api/user/signup.ts
- packages/mrgn-ui/src/components/wallet-v2/wallet.tsx
Check mrgnlend store is initialized before fetching from fb
> fix(mfi-v2-ui): fb perms error

- apps/marginfi-landing-page/src/app/layout.tsx
- apps/marginfi-v2-trading/src/pages/_app.tsx
- apps/marginfi-v2-ui/src/pages/_app.tsx
Adds HotJar tracking script to landing page, mfi, arena
> chore: add hotjar

- apps/marginfi-v2-trading/src/components/common/Header/Header.tsx
- apps/marginfi-v2-trading/src/context/TradeProvider.tsx
- apps/marginfi-v2-trading/src/pages/_app.tsx
- apps/marginfi-v2-trading/src/store/tradeStore.ts
- apps/marginfi-v2-ui/src/components/common/Navbar/Navbar.tsx
- apps/marginfi-v2-ui/src/context/MrgnlendProvider.tsx
- packages/mrgn-ui/src/components/wallet-v2/components/wallet-button/wallet-button.tsx
- packages/mrgn-ui/src/components/wallet-v2/wallet.tsx
Ensure user data is cleared when logging out of the arena and ensure user data is fully loaded before enabling wallet.
> fix: wallet loading improvements

- packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/components/action-input/components/loop-action/loop-action.tsx
- packages/mrgn-ui/src/components/action-box-v2/components/action-button/action-button.tsx
**Changelog:**
- Fixed loading animation
- Fixed max amount input
> feat(mfi-v2-ui): looper fixes

- apps/marginfi-v2-ui/src/pages/index.tsx
Using the unsorted marginfiClient.banks object to get the latest added bank and adding this to the announcements
> feat(mfi-v2-ui): adding the latest added bank to the announcements section

- apps/marginfi-v2-ui/src/components/common/Portfolio/components/asset-card/portfolio-asset-card.tsx
- packages/marginfi-v2-ui-state/src/lib/mrgnlend.ts
- Fixes isLending state to compare assets against liabs and account for dust
- Adds full balance to portfolio asset card
> fix(mfi-v2-ui): portfolio balances

- packages/mrgn-ui/src/components/action-box-v2/actions/lend-box/hooks/use-lend-simulation.hooks.ts
- packages/mrgn-ui/src/components/action-box-v2/actions/lend-box/lend-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/lend-box/store/lend-box-store.ts
- packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/hooks/use-loop-simulation.hooks.ts
- packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/loop-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/store/loop-store.ts
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-collat-box/hooks/use-repay-simulation.hooks.ts
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-collat-box/repay-collat-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-collat-box/store/repay-collat-store.ts
- packages/mrgn-ui/src/components/action-box-v2/actions/stake-box/hooks/use-stake-simulation.hooks.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/stake-box/stake-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/stake-box/store/stake-box-store.ts
- packages/mrgn-ui/src/components/action-box-v2/components/action-simulation-status/action-simuation-status.tsx
- packages/mrgn-utils/src/errors.ts
- simulations state is now insync with button loading state 
- if simulation is succesfull it won't disappear
> fix(mfi-v2-ui): simulation improvements

- packages/marginfi-v2-ui-state/src/lib/points.ts
This PR will change the points document reference from the firebase client, to the new points storing.
The change should be seamless. Please review the changes!
> Fix: Change the points document reference

- packages/mrgn-ui/src/components/action-box-v2/actions/lend-box/lend-box.tsx
- packages/mrgn-ui/src/components/action-message/action-message.tsx
- packages/mrgn-utils/src/errors.ts
Improved error / warning message copy through simulation, toasts, and action complete dialog
> chore(mfi-ui): transaction error / warning message copy

- apps/marginfi-v2-ui/src/components/common/Stake/components/stake-card.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/lend-box/components/action-input/action-input.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/components/action-input/action-input.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/loop-box/loop-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-collat-box/components/action-input/action-input.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-collat-box/repay-collat-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/stake-box/components/action-input/action-input.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/stake-box/components/action-input/components/stake-action/stake-action.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/stake-box/stake-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/components/action-wrappers/action-box-navigator.tsx
- packages/mrgn-ui/src/components/action-box-v2/components/action-wrappers/action-dialog-wrapper.tsx
- packages/mrgn-ui/src/components/action-box-v2/utils/stats-preview.utils.tsx
- packages/mrgn-ui/src/components/action-complete/screens/lending-screen.tsx
- packages/mrgn-ui/src/components/action-message/action-message.tsx
- **feat: copy usd valud to all action inputs**
- **feat: remove action box headings, adjust dialog padding**
- **fix: info action message label width**
- **feat: actionbox preview copy changes**
> feat(mfi-ui): various actionbox updates

- apps/marginfi-v2-ui/src/components/common/Portfolio/components/asset-card/portfolio-asset-card.tsx
- apps/marginfi-v2-ui/src/components/common/Portfolio/lending-portfolio.tsx
- packages/marginfi-client-v2/src/models/account/pure.ts
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-collat-box/components/action-input/action-input.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-collat-box/components/action-input/components/repay-action/repay-action.tsx
- packages/mrgn-ui/src/components/action-box-v2/components/action-input/bank-item/bank-item.tsx
- packages/mrgn-ui/src/components/action-box-v2/components/action-input/bank-list-command/bank-list-command.tsx
- packages/mrgn-ui/src/components/action-box-v2/components/action-wrappers/action-dialog-wrapper.tsx
- packages/mrgn-ui/src/components/action-message/action-message.tsx
- packages/mrgn-ui/src/components/bridge/mayan.tsx
- packages/mrgn-ui/src/components/swap/swap.tsx
- **fix: portfolio asset card value formatting improved support for small / large numbers**
- **fix: prevent infinite liquidation prices**
- **fix: using wrong token for usd value in collat repay input**
- **fix: action message line breaking**
- **fix: various a11y warnings**
> fix(mfi-v2-ui): various fixes and improvements

- packages/marginfi-v2-ui-state/src/lib/points.ts
- **Revert "chore: update fb doc"**
- **chore: remove log**
> chore(mfi-v2-ui): fb doc update

- apps/marginfi-v2-trading/src/components/common/trade-box-v2/components/amount-input/amount-input.tsx
- apps/marginfi-v2-trading/src/components/common/trade-box-v2/components/amount-input/components/max-action/max-action.tsx
- apps/marginfi-v2-trading/src/components/common/trade-box-v2/components/info-messages/info-messages.tsx
- apps/marginfi-v2-trading/src/components/common/trade-box-v2/components/stats/utils/stats-utils.tsx
- apps/marginfi-v2-trading/src/components/common/trade-box-v2/hooks/use-action-amounts.ts
- apps/marginfi-v2-trading/src/components/common/trade-box-v2/hooks/use-trade-simulation.ts
- apps/marginfi-v2-trading/src/components/common/trade-box-v2/trade-box.tsx
- apps/marginfi-v2-trading/src/components/common/trade-box-v2/utils/trade-action.utils.ts
- apps/marginfi-v2-trading/src/components/common/trade-box-v2/utils/trade-box.consts.ts
- apps/marginfi-v2-trading/src/store/tradeStoreV2.ts
- packages/marginfi-client-v2/src/models/account/types.ts
- packages/marginfi-client-v2/src/models/account/wrapper.ts
- packages/mrgn-common/src/modules/transactions/transaction.types.ts
- packages/mrgn-utils/src/actions/flashloans/builders.ts
- packages/mrgn-utils/src/actions/individualFlows.ts
- packages/mrgn-utils/src/actions/types.ts
This PR enables USDC only trading on the arena, making it more of a trade-like experience.
> feat(mfi-trading): Enable USDC trading

- apps/marginfi-v2-ui/src/pages/_app.tsx
- apps/marginfi-v2-ui/src/pages/migrate/account.tsx
- packages/marginfi-v2-ui-state/src/lib/firebase.ts
- packages/marginfi-v2-ui-state/src/lib/mrgnlend.ts
- packages/mrgn-utils/src/errors.ts
- **Revert "fix: bank total deposits / borrows calcs"**
- **chore: remove banner**
- **fix: phantom window provider points migration**
- **fix: account migration txn processing**
> fix(mfi-v2-ui): account migration / various hotfixes

- apps/marginfi-v2-ui/src/components/common/AssetList/AssetListFilters.utils.tsx
- packages/mrgn-ui/src/components/action-complete/screens/lending-screen.tsx
- packages/mrgn-utils/src/emissions.consts.ts
- **chore: update stable / lst lists**
- **chore: add susd emissions metadata**
- **feat: include emissions apy in action complete dialog**
> feature(mfi-v2-ui): emissions metadata update

- packages/mrgn-ui/src/components/action-box-v2/utils/stats-preview.utils.tsx
- Fix USD values in actionbox preview
- Fallback to amountIn calculation if Jup fails on exact out
> feature(mfi-v2-ui): collateral repay improvements

- apps/marginfi-v2-ui/src/components/common/Portfolio/components/rewards/rewards-dialog.tsx
- apps/marginfi-v2-ui/src/components/common/Portfolio/lending-portfolio.tsx
- **feat: trigger toast if rewards available**
- **feat: rewards dialog styling / copy changes**
- **feat: styling / copy changes for rewards dialog**
> feat(mfi-v2-ui): rewards ux

- packages/marginfi-client-v2/src/models/account/wrapper.ts
- packages/mrgn-utils/src/actions/flashloans/builders.ts
- fix makeLoopTx args
- Add unwrap ix for native mint
> fix(mfi-v2-ui): looping sol

- apps/marginfi-v2-trading/src/components/common/Pool/CreatePoolDialog/components/create-pool-configure.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/CreatePoolDialog/components/create-pool-loading/create-pool-loading.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/CreatePoolDialog/components/create-pool-review.tsx
- apps/marginfi-v2-trading/src/components/common/Pool/CreatePoolDialog/types.ts
- apps/marginfi-v2-trading/src/consts/bank-config.consts.ts
- apps/marginfi-v2-trading/src/utils/create-pools.utils.ts
- packages/marginfi-client-v2/src/idl/marginfi-types.ts
- packages/marginfi-client-v2/src/idl/marginfi.json
- packages/marginfi-client-v2/src/instructions.ts
- packages/marginfi-client-v2/src/models/bank.ts
- packages/marginfi-client-v2/src/models/group.ts
- added instruction to configure pool
- added new idl
- resolved all breaking changes
- updated the create pool arena flow
> feat: updated idl and implemented changes

- packages/mrgn-ui/src/components/action-box-v2/utils/stats-preview.utils.tsx
> chore(mrgn-v2-ui): remove console log

- packages/tools/accounts/get-account.ts
- packages/tools/banks/get-bank.ts
- packages/tools/lib/types.ts
- packages/tools/lib/utils.ts
- packages/tools/scripts/config_bank.ts
- Add "flags" to banks:get
- Fetch bank metadata from birdeye if not found
- Adds support for non-main group bank metadata 
- Bank config script mods
> feat(tools): add support for non-main group metadata

- packages/tools/README.md
> Add env details to tools readme

- apps/marginfi-v2-trading/src/components/common/Pool/pool-card.tsx
- apps/marginfi-v2-trading/src/components/common/Portfolio/PositionActionButtons.tsx
- apps/marginfi-v2-trading/src/components/common/Portfolio/PositionList/PositionList.tsx
- apps/marginfi-v2-trading/src/components/common/search/components/search-drawer.tsx
- apps/marginfi-v2-trading/src/components/common/search/components/search-list.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/add-position-box/add-position-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/add-position-box/components/preview/preview.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-box/components/preview/preview.tsx
- packages/mrgn-ui/src/components/action-box-v2/actions/repay-box/repay-box.tsx
- packages/mrgn-ui/src/components/action-box-v2/utils/stats-preview/preview-labels.utils.tsx
- packages/mrgn-ui/src/components/action-box-v2/utils/stats-preview/preview.utils.tsx
PR for small fixes / improvements during quality assurance.
> feat: The Arena QA
